/** Spiegel von src/features/chat/constants/documentSummaryPlaybook.ts — nur Playbook-Text. */
export function buildDocumentSummaryPlaybookEdge(): string {
  return [
    'Dokument-Zusammenfassung — Playbook (verbindlich, Lern-/Prüfungsziel):',
    '',
    'Inhaltliche Lieferung:',
    '- Liefere **Wissen, Fakten und Ergebnisse** aus dem Anhang — nicht beschreiben, **was das Dokument enthält**.',
    '- **VERBOTEN:** «Das Blatt/PDF/Dossier deckt/enthält/thematisiert/listet/beschreibt…», «Im Material geht es um…» ohne inhaltliche Ausarbeitung.',
    '- **VERBOTEN:** Kapitel, die nur **Themen oder Aufgabennummern** aufzählen (z. B. «Aufgaben 1–6 zu Steuern») ohne konkrete Lösung.',
    '- Schul-Material / Arbeitsblatt: **integriertes Lernskript** — alle Themen, Fragen und Übungen **inhaltlich ausgearbeitet**.',
    '- **Inhalt ja, Form nein:** Fragen beantworten, Lücken füllen, Rechenwege liefern — **ohne** «Aufgabe:», «Lösung:», «Musterlösung», «Aufgabenstellung:».',
    '- Kapitelüberschriften thematisch: `## Kindesverhältnis (ZGB)` — **nicht** `## Aufgabe 15` / `## Auftrag 5`.',
    '- Mathe: Rechenweg bis Ergebnis; offene Fragen: ausformulierte Antwort — nicht «der Schüler soll…».',
    '- Reiner Lesetext: Konzepte in **eigenen Worten** ausarbeiten — kein Inhaltsverzeichnis.',
    '',
    'Dichte — kompakt (alle Themen, wenig Fliesstext):',
    '- **Vollständigkeit ja, Wortzahl nein:** Jedes Pflicht-Thema abdecken — aber **knapp** formulieren wie Lernkarten, nicht wie Essay.',
    '- Pro Kachel `body`: **max. 2 kurze Sätze** ODER **2–4 eigene Zeilen** (je Zeile max. 12 Wörter) — **jeder Punkt = neue Zeile** im `body`-Feld, z. B. `**Ziel:** …` dann Zeilenumbruch `**Funktion:** …`.',
    '- **VERBOTEN:** mehrere Punkte in **einer** Zeile mit `·`, `;` oder `/` verketten — das wirkt kaputt in der UI.',
    '- **VERBOTEN:** Absätze >40 Wörter, Schachtelsätze, Wiederholungen, «im Wesentlichen geht es darum…».',
    '- **3+ Fakten** zum gleichen Thema → ```divided-list``` statt einem langen `body`-Absatz.',
    '- Kapitel-Einleitung: **max. 1 Halbsatz** (z. B. «Kurz: Steuerpflicht bei Kantonwechsel.») — kein zweiter Erklärabsatz.',
    '',
    'Visuelles Format (kompakt + farbig):',
    '- Beginne mit `## Zusammenfassung: [Thema]` + «Diese Zusammenfassung basiert auf deinem Dokument.»',
    '- Hauptteile: `## 1. …`, `## 2. …` — danach sofort Kacheln/Listen/Callouts.',
    '- Zwischen **jedem** Hauptthema eine eigene Zeile `---`.',
    '- **Jedes Thema** → ```cards``` mit `tone` (Farbe) und optional `badges` (Schlagwörter):',
    '  ```cards',
    '  tone: blue',
    '  label: Steuerrecht',
    '  title: Wegzug innerhalb der Schweiz',
    '  body: Wohnsitz am 31.12. bestimmt Kanton',
    '  Quellensteuer endet mit Abmeldung',
    '  badges: teal: Kantonwechsel | orange: Frist',
    '  ---',
    '  tone: green',
    '  label: Praxis',
    '  title: Was du beachten musst',
    '  body: Meldung beim neuen Kanton. Alte Steuerrechnung noch offen? → Zahlungsfrist prüfen.',
    '  badges: green: Checkliste',
    '  ```',
    '- `tone:` blue | teal | green | orange | purple | indigo — **abwechseln** pro Kachel.',
    '- `badges:` 1–3 kurze Tags mit Farbe (`blue: … | green: …`) — z. B. Frist, Gesetz, Praxis, Rechenweg.',
    '- `label:` kurz und als Kategorie (Steuerrecht, Praxis, Definition, Lösung) — UI rendert farbig.',
    '- In `body:` **niemals** «Aufgabe:»/«Lösung:» — nur kompakter Inhalt.',
    '- Lückentext → eine Kachel, body = ausgefüllter Text in **einem** Satz wenn möglich.',
    '- **3+ parallele Typen/Arten** → je Typ eine Kachel mit eigenem `tone`.',
    '- Glossar → Tabelle; Merksatz → `> !` / Tipp → `> ?` / Warnung → `> !!` (je **1** kurzer Satz).',
    '',
    'Qualitätsregeln (harte Prüfung):',
    '- Jede Kachel: `body` **ausgefüllt und kompakt** — nie nur `title`; nie leer; nie Riesenabsatz.',
    '- **VERBOTEN:** «nachschlagen», «in Statistiken», «typischerweise» ohne konkreten Inhalt aus dem Material.',
    '- **VERBOTEN:** unvollständige Abschnitte (Frage ohne Antwort, Lückentext ohne Ende, Callout mitten im Wort).',
    '- Zahlen, Beispiele und Begriffe aus dem Anhang **übernehmen** — nichts erfinden.',
    '- Kein leeres Kapitel am Ende; kein `### Verbesserungen`, keine Schluss-Anpassungsfrage.',
    '- `## Annahmen` (falls nötig): höchstens 1–3 Sätze — kein Kapitelverzeichnis.',
  ].join('\n')
}
